sudo: required
services:
  - docker

before_install:
  - docker build -t vladov/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true vladov/react-docker yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-309227111997"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
